; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.34"

; Modules
projects[acquia_connector][subdir] = "contrib"

projects[addressfield][subdir] = "contrib"

projects[admin_menu][subdir] = "contrib"

projects[backup_migrate][subdir] = "contrib"

projects[block_class][subdir] = "contrib"

projects[calendar][subdir] = "contrib"

projects[coffee][subdir] = "contrib"

projects[colorbox][subdir] = "contrib"

projects[content_access][subdir] = "contrib"

projects[context][subdir] = "contrib"

projects[ctools][subdir] = "contrib"

projects[date][subdir] = "contrib"

projects[devel][subdir] = "contrib"

projects[ds][subdir] = "contrib"

projects[elysia_cron][subdir] = "contrib"

projects[email][subdir] = "contrib"

projects[entity][subdir] = "contrib"

projects[entityreference][subdir] = "contrib"

projects[features][subdir] = "contrib"

projects[feeds][subdir] = "contrib"

projects[field_group][subdir] = "contrib"

projects[flag][subdir] = "contrib"

projects[flexslider][subdir] = "contrib"

projects[globalredirect][subdir] = "contrib"

projects[elysia_cron][subdir] = "contrib"

projects[hybridauth][subdir] = "contrib"

projects[insert][subdir] = "contrib"

projects[jquery_update][subdir] = "contrib"

projects[libraries][subdir] = "contrib"

projects[link][subdir] = "contrib"

projects[masquerade][subdir] = "contrib"

projects[maxlength][subdir] = "contrib"

projects[media][subdir] = "contrib"

projects[media_flickr][subdir] = "contrib"

projects[media_library][subdir] = "contrib"

projects[media_soundcloud][subdir] = "contrib"

projects[media_vimeo][subdir] = "contrib"

projects[media_youtube][subdir] = "contrib"

projects[menu_attributes][subdir] = "contrib"

projects[menu_block][subdir] = "contrib"

projects[menu_expanded][subdir] = "contrib"

projects[metatag][subdir] = "contrib"

projects[migrate][subdir] = "contrib"

projects[module_filter][subdir] = "contrib"

projects[multiform][subdir] = "contrib"

projects[nodequeue][subdir] = "contrib"

projects[oauth][subdir] = "contrib"

projects[owlcarousel][subdir] = "contrib"

projects[panels][subdir] = "contrib"

projects[pathauto][subdir] = "contrib"

projects[permission_select][subdir] = "contrib"

projects[permissions_lock][subdir] = "contrib"

projects[phpmailer][subdir] = "contrib"

projects[privatemsg][subdir] = "contrib"

projects[quicktabs][subdir] = "contrib"

projects[realname][subdir] = "contrib"

projects[references][subdir] = "contrib"

projects[rules][subdir] = "contrib"

projects[scheduler][subdir] = "contrib"

projects[select_or_other][subdir] = "contrib"

projects[sharethis][subdir] = "contrib"

projects[spambot][subdir] = "contrib"

projects[token][subdir] = "contrib"

projects[variable][subdir] = "contrib"

projects[views][subdir] = "contrib"

projects[views_bulk_operations][subdir] = "contrib"

projects[views_infinite_scroll][subdir] = "contrib"

projects[views_tree][subdir] = "contrib"

projects[votingapi][subdir] = "contrib"

projects[webform][subdir] = "contrib"

projects[webform_ajax][subdir] = "contrib"

projects[webform_optionsmarkup][subdir] = "contrib"

projects[webform_steps][subdir] = "contrib"

projects[webform_term_opts][subdir] = "contrib"

projects[wysiwyg][subdir] = "contrib"

projects[wysiwyg_filter][subdir] = "contrib"

projects[xmlsitemap][subdir] = "contrib"

projects[entityform][subdir] = "contrib"

projects[masonry][subdir] = "contrib"

projects[masonry_fields][subdir] = "contrib"

projects[masonry_fields][subdir] = "contrib"

projects[masonry_search][subdir] = "contrib"

projects[views_timelinejs][subdir] = "contrib"

projects[Field_formatter_settings][subdir] = "contrib"

; Themes

projects[] = "zen"

projects[] = "bootstrap"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[bgrins-spectrum][download][type] = ""
libraries[bgrins-spectrum][download][url] = ""
libraries[bgrins-spectrum][directory_name] = "bgrins-spectrum"
libraries[bgrins-spectrum][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[FlexSlider][download][type] = ""
libraries[FlexSlider][download][url] = ""
libraries[FlexSlider][directory_name] = "FlexSlider"
libraries[FlexSlider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[getlocations][download][type] = ""
libraries[getlocations][download][url] = ""
libraries[getlocations][directory_name] = "getlocations"
libraries[getlocations][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery-simple-color][download][type] = ""
libraries[jquery-simple-color][download][url] = ""
libraries[jquery-simple-color][directory_name] = "jquery-simple-color"
libraries[jquery-simple-color][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[masonry][download][type] = ""
libraries[masonry][download][url] = ""
libraries[masonry][directory_name] = "masonry"
libraries[masonry][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[Modernizr][download][type] = ""
libraries[Modernizr][download][url] = ""
libraries[Modernizr][directory_name] = "Modernizr"
libraries[Modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[owl-carousel][download][type] = ""
libraries[owl-carousel][download][url] = ""
libraries[owl-carousel][directory_name] = "owl-carousel"
libraries[owl-carousel][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[phpmailer][download][type] = ""
libraries[phpmailer][download][url] = ""
libraries[phpmailer][directory_name] = "phpmailer"
libraries[phpmailer][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[timeline][download][type] = ""
libraries[timeline][download][url] = ""
libraries[timeline][directory_name] = "timeline"
libraries[timeline][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

